### ISSUE TITLE
Parallax images of places

### ISSUE THREAD

**Issue by maxkeppeler** [MaximilianKeppeler/Places#6]
To make the scrolling more comfortable and stunning.  I can imagine that this is very complex to do, though I will try to get it done later.

**Comment by SubhrajyotiSen** [comment]
I can help with this

**Comment by maxkeppeler** [comment]
Really? I thought that's really complex and the adapter (here places adapter) must be changed very much. No rush at all, thanks for your help. You can add yourself as helper too. (strings_about.xml)

**Comment by SubhrajyotiSen** [comment]
I have used parallax images before. So I guess it won't be that difficult. 
I will get on it after my exams.

**Comment by SubhrajyotiSen** [comment]
Where exactly do you want the parallax images to be implemented?

**Comment by SubhrajyotiSen** [comment]
I have an implementation ready. Tell me where you want the parallax images

**Comment by maxkeppeler** [comment]
Well actually for the thumbnail images of the Places. (PlacesAdapter)
